version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.11.3-management
    container_name: projetoCloud_rabbitmq
    hostname: broker
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: projetoCloud_elasticsearch
    ports: 
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node      
    networks:
      - app-net
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: projetoCloud_kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - app-net  

  database:
    container_name: projetoCloud_postgres
    build: database
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/var/lib/postgresql'
    networks:
      - app-net

  authentication:
    container_name: projetoCloud_authentication
    build: authentication
    ports:
      - '4000:4000'
    depends_on:
      - database
      - rabbitmq
      - elasticsearch           
    networks:
      - app-net

  core:
    container_name: projetoCloud_core
    build: core
    ports:
      - '5000:5000'
    depends_on:
      - database
      - rabbitmq
      - elasticsearch
    networks:
      - app-net

  event:
    container_name: projetoCloud_event
    build: event
    ports:
      - '5001:5001'
    depends_on:
      - database
      - rabbitmq
      - elasticsearch   
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
  elastic:
    driver: bridge
    
volumes:
  postgresql_data:
    driver: local
  broker-secret: